SET SEREVEROUTPUT ON 

DECLARE
    v_salary NUMBER;
BEGIN
    SELECT BASIC_SALARY
    INTO v_salary
    FROM EMP
    WHERE EMP_ID = 9999;

    DBMS_OUTPUT.PUT_LINE('Salary = ' || v_salary);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SQLCODE = ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('SQLERRM = ' || SQLERRM);
END;
/